#!/usr/bin/env zsh
# Personal dependabot-equivalent for brew/asdf — Dependabot only reads repo
# manifest files (package.json, go.mod...), it has no concept of Homebrew or
# asdf, so this repo needs its own version-tracking script.
#
#   ./scripts/update_packages.zsh            # dry run
#   ./scripts/update_packages.zsh --apply             # upgrade + commit
#   ./scripts/update_packages.zsh --apply --push      # upgrade + commit + push
set -euo pipefail

repo_dir="$(cd "$(dirname "$0")/.." && pwd)"
lockfile="$repo_dir/manifests/package_versions.lock"
mode="--dry-run"
push=0
for arg in "$@"; do
  case "$arg" in
    --apply) mode="--apply" ;;
    --push) push=1 ;;
    *) print -r -- "error: unknown flag: $arg" >&2; exit 1 ;;
  esac
done

is_macos() { [ "$(uname -s)" = "Darwin" ] }

if [ "$mode" = "--apply" ]; then
  if is_macos && command -v brew >/dev/null 2>&1; then
    brew update
    brew upgrade
  fi
  if command -v asdf >/dev/null 2>&1; then
    asdf plugin update --all >/dev/null 2>&1 || true
  fi
else
  print -- "dry run: would run brew update/upgrade and asdf plugin update --all"
fi

{
  print -- "# generated by scripts/update_packages.zsh — do not edit by hand"
  if is_macos && command -v brew >/dev/null 2>&1; then
    brew list --versions | sed 's/^/brew /'
  fi
  if command -v asdf >/dev/null 2>&1; then
    asdf current 2>/dev/null | awk '{print "asdf " $1 " " $2}'
  fi
} > "$lockfile.new"

if [ "$mode" != "--apply" ]; then
  if diff -q "$lockfile" "$lockfile.new" >/dev/null 2>&1; then
    print -- "summary: no version changes"
  else
    print -- "summary: versions would change (dry run, nothing written)"
    diff "$lockfile" "$lockfile.new" 2>/dev/null || true
  fi
  rm -f "$lockfile.new"
  exit 0
fi

if diff -q "$lockfile" "$lockfile.new" >/dev/null 2>&1; then
  rm -f "$lockfile.new"
  print -- "summary: no version changes, nothing committed"
  exit 0
fi

mv "$lockfile.new" "$lockfile"
git -C "$repo_dir" add "$lockfile"
git -C "$repo_dir" commit -m "chore: update package versions" >/dev/null
print -- "summary: package_versions.lock updated and committed"

if [ "$push" -eq 1 ]; then
  git -C "$repo_dir" push
  print -- "pushed"
else
  print -- "run 'git push' when ready — this script never pushes unless you pass --push"
fi
